### ISSUE TITLE
Crash with Chisel2 2.5.1.44 and TCBotaniaExoflame v1.3

### ISSUE THREAD

**Issue by xeronut** [MatthiasMann/TCBotaniaExoflame#2]
http://pastebin.com/8cwiWDFG - Forge 1558

It looks as if the mod is looking for TeamChisel's version of Chisel and crashes when it doesn't find it.

**Comment by MatthiasMann** [comment]
Fixed by https://github.com/MatthiasMann/TCBotaniaExoflame/commit/cd7d903e5f0ec8682cc7d94ebe41c1cfa8628628
